import { keepPreviousData, queryOptions, useMutation, useQueryClient } from '@tanstack/react-query';
import { api, unwrap } from '@/api/client';
import { ApiError } from '@/api/errors';
import type { Order, OrderStatus, Payment } from '@/api/schema';

export const orderKeys = {
  all: ['orders'] as const,
  lists: () => [...orderKeys.all, 'list'] as const,
  list: (filters: { page: number; status?: OrderStatus }) =>
    [...orderKeys.lists(), filters] as const,
  detail: (id: string) => [...orderKeys.all, 'detail', id] as const,
  payments: (id: string) => [...orderKeys.all, 'detail', id, 'payments'] as const,
  invoice: (id: string) => [...orderKeys.all, 'detail', id, 'invoice'] as const,
};

export const ORDERS_PAGE_SIZE = 10;

export const ORDER_STATUSES = [
  'PENDING',
  'CONFIRMED',
  'PROCESSING',
  'SHIPPED',
  'DELIVERED',
  'CANCELLED',
] as const satisfies readonly OrderStatus[];

/** The happy path an order moves along; CANCELLED can branch off any step before SHIPPED. */
export const FULFILMENT_STEPS = [
  'PENDING',
  'CONFIRMED',
  'PROCESSING',
  'SHIPPED',
  'DELIVERED',
] as const satisfies readonly OrderStatus[];

/** States reached only after the payment was captured: the invoice job has run (or is about to). */
const PAID_STATUSES: readonly OrderStatus[] = ['CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED'];
export const isPaid = (status: OrderStatus) => PAID_STATUSES.includes(status);

/** Order list state from the URL; malformed values fall back instead of failing. */
export function parseOrderFilters(params: URLSearchParams): { page: number; status?: OrderStatus } {
  const page = Number(params.get('page'));
  const status = ORDER_STATUSES.find((value) => value === params.get('status'));
  return { page: Number.isInteger(page) && page >= 1 ? page : 1, ...(status && { status }) };
}

export function ordersQuery(filters: { page: number; status?: OrderStatus }) {
  return queryOptions({
    queryKey: orderKeys.list(filters),
    queryFn: () =>
      unwrap(
        api.GET('/api/v1/orders', {
          params: { query: { ...filters, pageSize: ORDERS_PAGE_SIZE } },
        }),
      ),
    placeholderData: keepPreviousData,
  });
}

export function orderQuery(id: string) {
  return queryOptions({
    queryKey: orderKeys.detail(id),
    queryFn: async () =>
      (await unwrap(api.GET('/api/v1/orders/{id}', { params: { path: { id } } }))).data,
  });
}

export function orderPaymentsQuery(id: string) {
  return queryOptions({
    queryKey: orderKeys.payments(id),
    queryFn: async () =>
      (await unwrap(api.GET('/api/v1/orders/{id}/payments', { params: { path: { id } } }))).data,
  });
}

const INVOICE_POLL_MS = 3000;
const INVOICE_MAX_POLLS = 10;

/**
 * The invoice is generated by a background job right after the payment is confirmed, so a paid
 * order can briefly have none: that is `null` (not an error), polled for a short while.
 */
export function invoiceQuery(order: Pick<Order, 'id' | 'status'>) {
  return queryOptions({
    queryKey: orderKeys.invoice(order.id),
    queryFn: async () => {
      try {
        return (
          await unwrap(
            api.GET('/api/v1/orders/{id}/invoice', { params: { path: { id: order.id } } }),
          )
        ).data;
      } catch (error) {
        if (error instanceof ApiError && error.code === 'INVOICE_NOT_FOUND') return null;
        throw error;
      }
    },
    enabled: order.status !== 'PENDING',
    refetchInterval: (query) =>
      query.state.data === null &&
      isPaid(order.status) &&
      query.state.dataUpdateCount < INVOICE_MAX_POLLS
        ? INVOICE_POLL_MS
        : false,
  });
}

/** Customers may cancel their own PENDING orders; the API decides (see `allowedTransitions`). */
export function useCancelOrder() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, reason }: { id: string; reason?: string }) =>
      (
        await unwrap(
          api.PATCH('/api/v1/orders/{id}/status', {
            params: { path: { id } },
            body: { status: 'CANCELLED', ...(reason && { reason }) },
          }),
        )
      ).data,
    onSuccess: (order) => {
      queryClient.setQueryData(orderKeys.detail(order.id), order);
      void queryClient.invalidateQueries({ queryKey: orderKeys.lists() });
    },
  });
}

/** Most recent payment attempt (the API lists newest first). */
export const latestPayment = (payments: Payment[] | undefined) => payments?.[0];

export function createOrder(addressId: string, idempotencyKey: string) {
  return unwrap(
    api.POST('/api/v1/orders', {
      body: { addressId },
      headers: { 'Idempotency-Key': idempotencyKey },
    }),
  ).then((r) => r.data);
}

export function createPayment(orderId: string, paymentMethod: string, idempotencyKey: string) {
  return unwrap(
    api.POST('/api/v1/payments', {
      body: { orderId, paymentMethod },
      // Required by the contract: the generated types make forgetting it a compile error.
      params: { header: { 'idempotency-key': idempotencyKey } },
    }),
  ).then((r) => r.data);
}
