import { expect, expectAccessible, test } from './fixtures';

test.describe('shopping', () => {
  test.beforeEach(async ({ loginAs, api }) => {
    // Start every test from an empty cart, whatever earlier tests left behind.
    const session = await loginAs('customer');
    await api(session, 'DELETE', '/api/v1/cart');
  });

  test('cart → shipping → review → payment → confirmation, paid through the real webhook', async ({
    page,
  }) => {
    await page.goto('/products/classic-canvas-sneakers');
    await page.getByRole('button', { name: 'Add to cart' }).click();
    await expect(page.getByText('Added to cart')).toBeVisible();

    await page.goto('/cart');
    await expect(
      page.getByRole('heading', { level: 2, name: 'Classic Canvas Sneakers' }),
    ).toBeVisible();
    await page.getByRole('link', { name: 'Proceed to checkout' }).click();

    await expect(
      page.getByRole('heading', { name: 'Where should we send your order?' }),
    ).toBeVisible();
    await expect(page.getByRole('radio', { checked: true })).toBeVisible();
    await page.getByRole('button', { name: 'Continue' }).click();

    await expect(page.getByRole('heading', { name: 'Review your order' })).toBeVisible();
    await page.getByRole('button', { name: /^Place order/ }).click();

    await expect(page.getByRole('heading', { name: 'Payment' })).toBeVisible();
    await expect(page.getByText('Test mode')).toBeVisible();
    await page.getByRole('radio', { name: 'Card declined' }).check();
    await page.getByRole('button', { name: /^Pay / }).click();
    await expect(
      page.getByText('The payment did not go through: card declined. You can try again.'),
    ).toBeVisible({ timeout: 30_000 });

    await page.getByRole('radio', { name: 'Successful payment' }).check();
    await page.getByRole('button', { name: /^Pay / }).click();
    // The worker delivers the provider webhook asynchronously; the page polls until it lands.
    await expect(page.getByText('Thank you! Your order is confirmed.')).toBeVisible({
      timeout: 30_000,
    });

    await page.getByRole('link', { name: 'View order details' }).click();
    await expect(page.getByRole('heading', { level: 1, name: /^Order ORD-/ })).toBeVisible();
    await expect(
      page.getByRole('main').getByText('Confirmed', { exact: true }).first(),
    ).toBeVisible();
    // The invoice is generated by a background job after the payment.
    await expect(page.getByRole('button', { name: /^View invoice INV-/ })).toBeVisible({
      timeout: 30_000,
    });
    await expectAccessible(page);
  });

  test('wishlist: save from the product page, then move to the cart', async ({ page }) => {
    await page.goto('/products/nimbus-x-phone');
    const save = page.getByRole('main').getByRole('button', { name: 'Save to wishlist' }).first();
    if ((await save.getAttribute('aria-pressed')) !== 'true') await save.click();
    await expect(save).toHaveAttribute('aria-pressed', 'true');

    await page.goto('/wishlist');
    await expect(page.getByRole('link', { name: 'Nimbus X Phone', exact: true })).toBeVisible();
    await expectAccessible(page);
  });
});

test.describe('account', () => {
  test('orders and profile pages are accessible', async ({ page, loginAs }) => {
    await loginAs('customer');
    for (const [path, heading] of [
      ['/orders', 'Orders'],
      ['/profile', 'Your account'],
      ['/cart', 'Cart'],
    ] as const) {
      await page.goto(path);
      await expect(page.getByRole('heading', { level: 1, name: heading })).toBeVisible();
      await page.waitForLoadState('networkidle');
      await expectAccessible(page);
    }
  });

  test('customer cancels a pending order', async ({ page, loginAs, api }) => {
    const session = await loginAs('customer');
    // Arrange through the API: one item in the cart, then an order awaiting payment.
    const product = (await (
      await api(session, 'GET', '/api/v1/products/classic-canvas-sneakers')
    ).json()) as { data: { variants: { id: string; inStock: boolean }[] } };
    const variant = product.data.variants.find((v) => v.inStock);
    expect(variant).toBeDefined();
    await api(session, 'DELETE', '/api/v1/cart');
    await api(session, 'POST', '/api/v1/cart/items', { variantId: variant?.id, quantity: 1 });
    const addresses = (await (await api(session, 'GET', '/api/v1/users/me/addresses')).json()) as {
      data: { id: string }[];
    };
    const created = await fetch(
      `${process.env.E2E_API_URL ?? 'http://localhost:3000'}/api/v1/orders`,
      {
        method: 'POST',
        headers: {
          authorization: `Bearer ${session.accessToken}`,
          'content-type': 'application/json',
          'idempotency-key': crypto.randomUUID(),
        },
        body: JSON.stringify({ addressId: addresses.data[0]?.id }),
      },
    );
    expect(created.status).toBe(201);
    const order = ((await created.json()) as { data: { id: string; orderNumber: string } }).data;

    await page.goto(`/orders/${order.id}`);
    await page.getByRole('button', { name: 'Cancel order' }).click();
    const dialog = page.getByRole('dialog', { name: `Cancel order ${order.orderNumber}?` });
    await dialog.getByRole('textbox', { name: 'Reason' }).fill('Ordered by mistake');
    await dialog.getByRole('button', { name: 'Cancel order' }).click();

    await expect(page.getByText(`Order ${order.orderNumber} cancelled`)).toBeVisible();
    await expect(page.getByText('Reason: Ordered by mistake')).toBeVisible();
    await expect(page.getByRole('heading', { level: 1 })).toBeFocused();
  });
});
